#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config window_shadow                off
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# window opacities
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.1
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95

# window borders
yabai -m config window_border                off
yabai -m config window_border_width          0.1
yabai -m config active_window_border_color   0x00292929
yabai -m config normal_window_border_color   0x00292929

# general space settings
yabai -m config layout                       float
yabai -m config top_padding                  36
yabai -m config bottom_padding               18
yabai -m config left_padding                 18
yabai -m config right_padding                18
yabai -m config window_gap                   18


# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


# rules
# exceptions
yabai -m rule --add app='^Spotify$' manage=on
yabai -m rule --add app='^Signal$' manage=off
yabai -m rule --add app='^Preview$' manage=off
yabai -m rule --add app='^macfeh$' manage=off
yabai -m rule --add app='^Finder$' manage=on
yabai -m rule --add app='^Photoshop$' manage=off
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^Cisco AnyConnect Secure Mobility Client$' manage=off

yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off

# more scripts
yabai -m signal --add label=float_next app='^iTerm2$' event=window_created action='yabai -m signal --remove float_next; yabai -m window $YABAI_WINDOW_ID --toggle float'
yabai -m signal --add event=application_launched action="/usr/local/Cellar/yabai/scripts/centreOneApp.sh"
yabai -m signal --add event=window_created action="/usr/local/Cellar/yabai/scripts/centreOneApp.sh"
yabai -m signal --add event=application_terminated action="/usr/local/Cellar/yabai/scripts/centreOneApp.sh"
yabai -m signal --add event=window_destroyed action="/usr/local/Cellar/yabai/scripts/centreOneApp.sh"

echo "yabai configuration loaded.."
